### ISSUE TITLE
Locale in formatter

### ISSUE THREAD

**Issue by VadymPinchuk** [fadhly-permata/flutter_money_formatter#15]
**Describe the bug**
I had NumberFormatException, while using your lib on my Ukrainian locale.

**Additional context**
I was not able to push changes in any branch an make a PR, so I forked, but it have sense to make a PR and hold all stuff in one place. So please, give me a response, when and how I can contribute. Thanks

**Comment by fadhly-permata** [comment]
Hi, currently I am so busy with my deadline 😬 ,

I will merging all PR on this weekend, You can create PR from [here](https://github.com/fadhly-permata/flutter_money_formatter/pulls)
