### ISSUE TITLE
Support intl 0.16.0

### ISSUE THREAD

**Issue by den-ree** [fadhly-permata/flutter_money_formatter#16]
**Overview**
After I updated the project to the stable channel, I have started getting the following error:

> Because flutter_money_formatter >=0.8.2 depends on intl ^0.15.8 and every version of flutter_localizations from sdk depends on intl 0.16.0, flutter_money_formatter >=0.8.2 is incompatible with flutter_localizations from sdk.
> 
> So, because bcmd_end_client_app_flutter depends on both flutter_localizations any from sdk and flutter_money_formatter ^0.8.3, version  

_Current version_

```
Flutter (Channel master, v1.10.6-pre.39, on Mac OS X 10.14.5 18F132, locale en-NL)
    • Flutter version 1.10.6-pre.39 at /Users/denree/Projects/Others.../Flutter/flutter
    • Framework revision 4815b26d71 (3 hours ago), 2019-09-24 00:21:44 -0700
    • Engine revision 953ac71749
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d53d355c6c)
```

**Comment by fadhly-permata** [comment]
You need to down-grade your `Intl` to version ^0.15.8.

I'll update the `Intl` dependency on the next release.

**Comment by den-ree** [comment]
@fadhly-permata I would like to downgrade the version, but on the stable version which is used in the app, `flutter_localizations` required 0.16.0. Or I misunderstand something?

**Comment by shabeenabarde** [comment]
> You need to down-grade your `Intl` to version ^0.15.8.
> 
> I'll update the `Intl` dependency on the next release.

Was this done? Because I am still getting the error.
