### ISSUE TITLE
Flutter Money Formatter is not compatible with intl 0.16.1

### ISSUE THREAD

**Issue by mukkulsingh** [fadhly-permata/flutter_money_formatter#25]
**Describe the bug**
Running "flutter pub get" in fitway_crm...                      
Because flutter_money_formatter >=0.8.2 depends on intl ^0.15.8 and flutter_money_formatter <0.8.2 depends on intl ^0.15.7, every version of flutter_money_formatter requires intl ^0.15.7.

And because every version of flutter_localizations from sdk depends on intl 0.16.0, flutter_money_formatter is incompatible with flutter_localizations from sdk.

So, because fitway_crm depends on both flutter_localizations any from sdk and flutter_money_formatter any, version solving failed.
pub get failed (1; So, because fitway_crm depends on both flutter_localizations any from sdk and flutter_money_formatter any, version solving failed.)
Process finished with exit code 1

**Comment by w4ll3** [comment]
There is already an open pull request that solves this bug (#23). As for now you can reference the branch directly in your `pubspec.yaml` file in this way:
```yaml
  flutter_money_formatter:
    git:
      url: git://github.com/anisalibegic/flutter_money_formatter.git
```
