### ISSUE TITLE
How to change amount

### ISSUE THREAD

**Issue by monxarat** [fadhly-permata/flutter_money_formatter#37]
Hi guys,

How to change the amount

**Comment by fadhly-permata** [comment]
Hi @monxarat ,

As described [here](https://github.com/fadhly-permata/flutter_money_formatter#getting-started),

You can change the amount from initialization, like follow:

`
FlutterMoneyFormatter fmf = FlutterMoneyFormatter(
    amount: 12345678.9012345
);
` 

And you can change it later, by assigning like below:

`
fmf.amount = 23456.1234
`
