### ISSUE TITLE
FormatException thrown when I used Indonesia language as the app localisations

### ISSUE THREAD

**Issue by dwhub** [fadhly-permata/flutter_money_formatter#9]
FormatException is thrown when I used Indonesia language as the Applocalizations in both iOS and Android. It was working fine if I set the device language to English but when I switch to Indonesia language I got this FormatException(2, 32).

**To Reproduce**
1. Create flutter app localisations (in this case I use "en", and "id")
2. Go to Settings in iOS device or Android device emulator
3. Switch the language to Indonesia
4. Start the app and you will see the format exception error.

**Expected behavior**
The money value should be formatted correctly regardless of the language.

**Screenshots**
<img width="1308" alt="Screen Shot 2019-08-18 at 10 46 13 am" src="https://user-images.githubusercontent.com/45648767/63219870-806e7d00-c1a5-11e9-804e-d903fc6b49ec.png">

**Smartphone (please complete the following information):**
 - Device: Android and iOS emulator

**Comment by Gerrel** [comment]
Fix is available with pull request: https://github.com/fadhly-permata/flutter_money_formatter/pull/8#issue-307499754

**Comment by fadhly-permata** [comment]
@Gerrel: Thanks for your contribution, I'll check this out, when everything is OK, then I'll merge it on the main branch 👍

**Comment by fadhly-permata** [comment]
@dwhub: Fixed by @Gerrel, and have been released ([v0.8.3](https://pub.dev/packages/flutter_money_formatter/versions/0.8.3))
